# Automatically generated by Pynguin.
import pytest
import blood_sugar_algorithm_refactored as module_0
import datetime as module_1

@pytest.mark.xfail
def test_case_0():
    int_0 = 1187
    int_1 = -1153
    str_0 = 'Z34:fxKnPl6.1aSqUA7'
    none_type_0 = None
    module_0.BloodSugar(int_0, int_1, str_0, none_type_0)

@pytest.mark.xfail
def test_case_1():
    int_0 = -1159
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    none_type_0 = None
    module_0.BloodSugar(int_0, int_0, none_type_0, datetime_0)

def test_case_2():
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    none_type_0 = None
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(none_type_0)
    assert bool_0 is True

def test_case_3():
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']

def test_case_4():
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']

@pytest.mark.xfail
def test_case_5():
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    blood_sugar_algorithm_0.init_data()

@pytest.mark.xfail
def test_case_6():
    none_type_0 = None
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    blood_sugar_algorithm_0.run(none_type_0)

@pytest.mark.xfail
def test_case_7():
    int_0 = 495
    str_0 = "?=\rhlDT+.qn''f>]A"
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    module_0.BloodSugar(int_0, int_0, str_0, datetime_0)

@pytest.mark.xfail
def test_case_8():
    int_0 = 495
    str_0 = 'FBS'
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, datetime_0)
    assert blood_sugar_0.blood_sugar == 495
    assert blood_sugar_0.temperature == 495
    assert blood_sugar_0.measure_state == 'FBS'
    assert module_1.MINYEAR == 1
    assert module_1.MAXYEAR == 9999
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_0 is True
    int_1 = 0
    blood_sugar_algorithm_0.set_prev_bs_info(int_1, datetime_0, str_0)

@pytest.mark.xfail
def test_case_9():
    int_0 = 495
    str_0 = 'FBS'
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, datetime_0)
    assert blood_sugar_0.blood_sugar == 495
    assert blood_sugar_0.temperature == 495
    assert blood_sugar_0.measure_state == 'FBS'
    assert module_1.MINYEAR == 1
    assert module_1.MAXYEAR == 9999
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_0 is True
    datetime_1 = module_0.random_datetime()
    blood_sugar_algorithm_0.check_super_high_bs(blood_sugar_0)

def test_case_10():
    int_0 = 495
    str_0 = 'FBS'
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, datetime_0)
    assert blood_sugar_0.blood_sugar == 495
    assert blood_sugar_0.temperature == 495
    assert blood_sugar_0.measure_state == 'FBS'
    assert module_1.MINYEAR == 1
    assert module_1.MAXYEAR == 9999
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_0 is True
    bool_1 = blood_sugar_algorithm_0.check_prev_bs(blood_sugar_0)
    assert bool_1 is True

@pytest.mark.xfail
def test_case_11():
    int_0 = 90
    str_0 = 'FBS'
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, datetime_0)
    assert blood_sugar_0.blood_sugar == 90
    assert blood_sugar_0.temperature == 90
    assert blood_sugar_0.measure_state == 'FBS'
    assert module_1.MINYEAR == 1
    assert module_1.MAXYEAR == 9999
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_0 is True
    bool_1 = blood_sugar_algorithm_0.check_prev_bs(blood_sugar_0)
    assert bool_1 is True
    bool_2 = blood_sugar_algorithm_0.check_super_high_bs(blood_sugar_0)
    assert bool_2 is True
    blood_sugar_algorithm_1 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_1.patient is None
    assert blood_sugar_algorithm_1.hypoglycemia is None
    assert blood_sugar_algorithm_1.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_1.abnormal_bs is None
    assert blood_sugar_algorithm_1.emergency_alarm is None
    assert blood_sugar_algorithm_1.bs_type is None
    assert blood_sugar_algorithm_1.new_measurement_required is None
    assert blood_sugar_algorithm_1.new_measurement_duration_min is None
    assert blood_sugar_algorithm_1.graphic_asset is None
    assert blood_sugar_algorithm_1.message_list == []
    assert blood_sugar_algorithm_1.last_bs is None
    blood_sugar_algorithm_1.init_data()

@pytest.mark.xfail
def test_case_12():
    int_0 = 141
    str_0 = 'FBS'
    datetime_0 = module_0.random_datetime()
    assert module_0.SPACE == ' '
    assert module_0.VALID_STATES == ['RBS', 'FBS', 'PBS', 'PLS', 'PDS']
    int_1 = 6
    blood_sugar_0 = module_0.BloodSugar(int_1, int_0, str_0, datetime_0)
    assert blood_sugar_0.blood_sugar == 6
    assert blood_sugar_0.temperature == 141
    assert blood_sugar_0.measure_state == 'FBS'
    assert module_1.MINYEAR == 1
    assert module_1.MAXYEAR == 9999
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_0 is True
    blood_sugar_algorithm_0.check_prev_bs(blood_sugar_0)