# Automatically generated by Pynguin.
import pytest
import blood_sugar_algorithm_refactored as module_0

@pytest.mark.xfail
def test_case_0():
    int_0 = 1840
    str_0 = 'u^TnP22m9bcNF*!9-Bz%'
    none_type_0 = None
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, none_type_0)
    assert blood_sugar_0.blood_sugar == 1840
    assert blood_sugar_0.temperature == 1840
    assert blood_sugar_0.measure_state == 'u^TnP22m9bcNF*!9-Bz%'
    assert blood_sugar_0.measure_time is None
    assert module_0.SPACE == ' '
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.check_prev_bs(blood_sugar_0)
    assert bool_0 is True
    bool_1 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_1 is True
    blood_sugar_algorithm_1 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_1.patient is None
    assert blood_sugar_algorithm_1.hypoglycemia is None
    assert blood_sugar_algorithm_1.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_1.abnormal_bs is None
    assert blood_sugar_algorithm_1.emergency_alarm is None
    assert blood_sugar_algorithm_1.bs_type is None
    assert blood_sugar_algorithm_1.new_measurement_required is None
    assert blood_sugar_algorithm_1.new_measurement_duration_min is None
    assert blood_sugar_algorithm_1.graphic_asset is None
    assert blood_sugar_algorithm_1.message_list == []
    assert blood_sugar_algorithm_1.last_bs is None
    blood_sugar_algorithm_2 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_2.patient is None
    assert blood_sugar_algorithm_2.hypoglycemia is None
    assert blood_sugar_algorithm_2.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_2.abnormal_bs is None
    assert blood_sugar_algorithm_2.emergency_alarm is None
    assert blood_sugar_algorithm_2.bs_type is None
    assert blood_sugar_algorithm_2.new_measurement_required is None
    assert blood_sugar_algorithm_2.new_measurement_duration_min is None
    assert blood_sugar_algorithm_2.graphic_asset is None
    assert blood_sugar_algorithm_2.message_list == []
    assert blood_sugar_algorithm_2.last_bs is None
    blood_sugar_algorithm_2.check_super_high_bs(blood_sugar_0)

def test_case_1():
    int_0 = -713
    str_0 = '/*yc&)u\nPv'
    none_type_0 = None
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, none_type_0)
    assert blood_sugar_0.blood_sugar == -713
    assert blood_sugar_0.temperature == -713
    assert blood_sugar_0.measure_state == '/*yc&)u\nPv'
    assert blood_sugar_0.measure_time is None
    assert module_0.SPACE == ' '
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.check_super_high_bs(blood_sugar_0)
    assert bool_0 is True

def test_case_2():
    none_type_0 = None
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    bool_0 = blood_sugar_algorithm_0.normal_person_bs(none_type_0)
    assert bool_0 is True

def test_case_3():
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '

def test_case_4():
    int_0 = 994
    int_1 = -59
    str_0 = ''
    none_type_0 = None
    blood_sugar_0 = module_0.BloodSugar(int_0, int_1, str_0, none_type_0)
    assert blood_sugar_0.blood_sugar == 994
    assert blood_sugar_0.temperature == -59
    assert blood_sugar_0.measure_state == ''
    assert blood_sugar_0.measure_time is None
    assert module_0.SPACE == ' '

@pytest.mark.xfail
def test_case_5():
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    blood_sugar_algorithm_1 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_1.patient is None
    assert blood_sugar_algorithm_1.hypoglycemia is None
    assert blood_sugar_algorithm_1.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_1.abnormal_bs is None
    assert blood_sugar_algorithm_1.emergency_alarm is None
    assert blood_sugar_algorithm_1.bs_type is None
    assert blood_sugar_algorithm_1.new_measurement_required is None
    assert blood_sugar_algorithm_1.new_measurement_duration_min is None
    assert blood_sugar_algorithm_1.graphic_asset is None
    assert blood_sugar_algorithm_1.message_list == []
    assert blood_sugar_algorithm_1.last_bs is None
    blood_sugar_algorithm_1.init_data()

@pytest.mark.xfail
def test_case_6():
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    assert module_0.SPACE == ' '
    none_type_0 = None
    blood_sugar_algorithm_0.run(none_type_0)

@pytest.mark.xfail
def test_case_7():
    int_0 = 44
    str_0 = 'N Ev6^,!`C<x&M@\nl.]c'
    none_type_0 = None
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, none_type_0)
    assert blood_sugar_0.blood_sugar == 44
    assert blood_sugar_0.temperature == 44
    assert blood_sugar_0.measure_state == 'N Ev6^,!`C<x&M@\nl.]c'
    assert blood_sugar_0.measure_time is None
    assert module_0.SPACE == ' '
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    blood_sugar_algorithm_0.check_prev_bs(blood_sugar_0)

@pytest.mark.xfail
def test_case_8():
    int_0 = 1840
    str_0 = ''
    none_type_0 = None
    blood_sugar_0 = module_0.BloodSugar(int_0, int_0, str_0, none_type_0)
    assert blood_sugar_0.blood_sugar == 1840
    assert blood_sugar_0.temperature == 1840
    assert blood_sugar_0.measure_state == ''
    assert blood_sugar_0.measure_time is None
    assert module_0.SPACE == ' '
    blood_sugar_algorithm_0 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_0.patient is None
    assert blood_sugar_algorithm_0.hypoglycemia is None
    assert blood_sugar_algorithm_0.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_0.abnormal_bs is None
    assert blood_sugar_algorithm_0.emergency_alarm is None
    assert blood_sugar_algorithm_0.bs_type is None
    assert blood_sugar_algorithm_0.new_measurement_required is None
    assert blood_sugar_algorithm_0.new_measurement_duration_min is None
    assert blood_sugar_algorithm_0.graphic_asset is None
    assert blood_sugar_algorithm_0.message_list == []
    assert blood_sugar_algorithm_0.last_bs is None
    bool_0 = blood_sugar_algorithm_0.check_prev_bs(blood_sugar_0)
    assert bool_0 is True
    bool_1 = blood_sugar_algorithm_0.normal_person_bs(blood_sugar_0)
    assert bool_1 is True
    blood_sugar_algorithm_1 = module_0.BloodSugarAlgorithm()
    assert blood_sugar_algorithm_1.patient is None
    assert blood_sugar_algorithm_1.hypoglycemia is None
    assert blood_sugar_algorithm_1.persistent_hypoglycemia is None
    assert blood_sugar_algorithm_1.abnormal_bs is None
    assert blood_sugar_algorithm_1.emergency_alarm is None
    assert blood_sugar_algorithm_1.bs_type is None
    assert blood_sugar_algorithm_1.new_measurement_required is None
    assert blood_sugar_algorithm_1.new_measurement_duration_min is None
    assert blood_sugar_algorithm_1.graphic_asset is None
    assert blood_sugar_algorithm_1.message_list == []
    assert blood_sugar_algorithm_1.last_bs is None
    blood_sugar_algorithm_1.diabetic_persons_bs(blood_sugar_0)